---
- name: Unarchive server files
  unarchive:
    src: Submission3/artifact.tar.gz
    dest: /home/ubuntu

- name: Start app
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start